"""
COMPLETE SUMMARY OF ANSWERS TO ALL QUESTIONS (1-11)
Master's in AI - Fundamentals of AI
Topic: Learning from Observations - Decision Tree Learning
"""

print("=" * 100)
print("COMPLETE SUMMARY: ALL ANSWERS (QUESTIONS 1-11)")
print("=" * 100)
print()

# ============= QUESTION 1 =============
print("QUESTION 1: Initial Entropy (H(S))")
print("-" * 100)
print("Question: 'The Entropy of the current dataset (without doing anything) is __ (provide exact calculated values)'")
print()
print("✓ ANSWER: 0.9710")
print()
print("Calculation:")
print("  Dataset: 5 examples total")
print("  Class distribution: 3 examples of Class 0, 2 examples of Class 1")
print("  H(S) = -(3/5 × log₂(3/5) + 2/5 × log₂(2/5))")
print("  H(S) = -(0.6 × (-0.737) + 0.4 × (-1.322))")
print("  H(S) = -(-0.442 - 0.529) = 0.9710")
print()
print()

# ============= QUESTION 2 =============
print("QUESTION 2: Information Gain with A1")
print("-" * 100)
print("Question: 'If we use A1 as our first split feature, the information gain will be __'")
print()
print("✓ ANSWER: 0.1710")
print()
print("Calculation:")
print("  Split on A1:")
print("    A1=0: 1 example (x3) → Class 0 only → H(S₀) = 0.0000")
print("    A1=1: 4 examples (x1,x2,x4,x5) → 2 Class 0, 2 Class 1 → H(S₁) = 1.0000")
print("  Weighted Entropy = (1/5)×0.0000 + (4/5)×1.0000 = 0.8000")
print("  IG(A1) = 0.9710 - 0.8000 = 0.1710")
print()
print()

# ============= QUESTION 3 =============
print("QUESTION 3: Information Gain with A2")
print("-" * 100)
print("Question: 'If we use A2 as our first split feature, the information gain will be __'")
print()
print("✓ ANSWER: 0.4200")
print()
print("Calculation:")
print("  Split on A2:")
print("    A2=0: 2 examples (x1,x2) → Class 0 only → H(S₀) = 0.0000 (PURE)")
print("    A2=1: 3 examples (x3,x4,x5) → 1 Class 0, 2 Class 1 → H(S₁) = 0.9183")
print("  Weighted Entropy = (2/5)×0.0000 + (3/5)×0.9183 = 0.5510")
print("  IG(A2) = 0.9710 - 0.5510 = 0.4200")
print()
print("  ✓ BEST SPLIT (Highest Information Gain)")
print()
print()

# ============= QUESTION 4 =============
print("QUESTION 4: Information Gain with A3")
print("-" * 100)
print("Question: 'If we use A3 as our first split feature, the information gain will be __'")
print()
print("✓ ANSWER: 0.0200")
print()
print("Calculation:")
print("  Split on A3:")
print("    A3=0: 3 examples (x1,x3,x5) → 2 Class 0, 1 Class 1 → H(S₀) = 0.9183")
print("    A3=1: 2 examples (x2,x4) → 1 Class 0, 1 Class 1 → H(S₁) = 1.0000")
print("  Weighted Entropy = (3/5)×0.9183 + (2/5)×1.0000 = 0.9510")
print("  IG(A3) = 0.9710 - 0.9510 = 0.0200")
print()
print("  ✗ WORST SPLIT (Lowest Information Gain)")
print()
print()

# ============= QUESTION 5 =============
print("QUESTION 5: First Split Attribute")
print("-" * 100)
print("Question: 'What is the attribute should be used in the first split?'")
print("Options: A1 / A2 / A3")
print()
print("✓ ANSWER: A2")
print()
print("Reasoning:")
print("  Information Gain Comparison:")
print("    IG(A1) = 0.1710")
print("    IG(A2) = 0.4200 ← MAXIMUM")
print("    IG(A3) = 0.0200")
print()
print("  Decision trees select the attribute with the HIGHEST Information Gain.")
print()
print()

# ============= QUESTION 6 =============
print("QUESTION 6: Second Split Attribute")
print("-" * 100)
print("Question: 'What is the attribute should be used in the second split?'")
print("Options: A1 / A2 / A3")
print()
print("✓ ANSWER: A1")
print()
print("Reasoning:")
print("  After A2 splits:")
print("    A2=0 branch: [x1, x2] → both Class 0 (PURE) ✓ No further split needed")
print()
print("  On A2=1 branch: [x3, x4, x5] → mixed (1 Class 0, 2 Class 1)")
print("    Remaining attribute options: A1, A3")
print()
print("    IG(A1 | A2=1) = 0.9183  ← MAXIMUM (perfectly separates classes)")
print("    IG(A3 | A2=1) = 0.2516")
print()
print("  A1 is selected for the second split.")
print()
print()

# ============= QUESTION 7 =============
print("QUESTION 7: Final Decision Tree")
print("-" * 100)
print("Question: 'Draw your final decision tree'")
print()
print("✓ ANSWER: (Tree Structure)")
print()
print("Tree Diagram:")
print("""
                           ROOT
                            |
                          [A2]
                         /    \\
                    A2=0/      \\A2=1
                      /        \\
                   [0]        [A1]
                 (Pure)       /   \\
                       A1=0 /     \\ A1=1
                         /        \\
                       [0]        [A3]
                     (Pure)       /  \\
                           A3=0 /    \\ A3=1
                             /        \\
                           [0]        [1]
                        (Pure)     (Pure)
""")
print()
print("Classification Rules:")
print("  1. If A2 = 0 → Predict Class 0")
print("  2. If A2 = 1:")
print("       If A1 = 0 → Predict Class 0")
print("       If A1 = 1:")
print("            If A3 = 0 → Predict Class 0")
print("            If A3 = 1 → Predict Class 1")
print()
print()

# ============= QUESTION 8 =============
print("QUESTION 8: Mixed Leaf Node Prediction")
print("-" * 100)
print("Question: 'When mixed positive & negative examples remain at leaf node,")
print("after all attributes are used, which solution minimizes absolute error?'")
print()
print("✓ ANSWER: Majority classification minimizes absolute error")
print()
print("Explanation:")
print("  When a leaf has p positive and n negative examples:")
print("    - If predict positive (=1): Misclassify n examples (all negatives)")
print("    - If predict negative (=0): Misclassify p examples (all positives)")
print()
print("  Majority classification chooses the label with highest count:")
print("    - If p > n: Predict positive (error = n)")
print("    - If n > p: Predict negative (error = p)")
print("    - If p = n: Predict either (error = p = n)")
print()
print("  This minimizes absolute error = min(p, n)")
print()
print()

# ============= QUESTION 9 =============
print("QUESTION 9: Absolute Error Formula")
print("-" * 100)
print("Question: 'If prediction is 1 (or 0), how is absolute error calculated?'")
print()
print("✓ ANSWER: If prediction ∈ {1}: then absolute error is p + 0 × n = n")
print("          If prediction ∈ {0}: then absolute error is n + 0 × p = p")
print()
print("Explanation:")
print("  For leaf with p positive and n negative examples:")
print()
print("  Prediction = 1:")
print("    - Correct positives: p × 1 = p")
print("    - Incorrect negatives: n × 1 = n")
print("    - Total error: 0 × p + 1 × n = n")
print()
print("  Prediction = 0:")
print("    - Correct negatives: n × 1 = n")
print("    - Incorrect positives: p × 1 = p")
print("    - Total error: 1 × p + 0 × n = p")
print()
print()

# ============= QUESTION 10 =============
print("QUESTION 10: Sum of Squared Errors (SSE)")
print("-" * 100)
print("Question: 'What is the sum of squared errors in terms of a?'")
print("(where a = ŷ = predicted value, y_i = actual values)")
print()
print("✓ ANSWER: SSE = ∑y_i² - 2ŷ∑y_i + p×ŷ²")
print()
print("Explanation:")
print("  The standard sum of squared residuals formula:")
print()
print("  SSE = ∑(y_i - ŷ)²")
print()
print("  Expanding the square:")
print("  SSE = ∑(y_i² - 2y_i×ŷ + ŷ²)")
print("      = ∑y_i² - 2ŷ∑y_i + p×ŷ²")
print()
print("  This is a quadratic function in ŷ with minimum at ŷ = mean(y)")
print()
print()

# ============= QUESTION 11 =============
print("QUESTION 11: Second Derivative and Monotonicity")
print("-" * 100)
print("Question: 'Regarding SSE derivatives and monotonic properties, which is correct?'")
print()
print("✓ ANSWER: The second derivative of sum of squared errors is monotonic increasing")
print()
print("Mathematical Proof:")
print()
print("  Given: SSE(ŷ) = ∑y_i² - 2ŷ∑y_i + p×ŷ²")
print()
print("  First Derivative:")
print("  d(SSE)/dŷ = 0 - 2∑y_i + 2p×ŷ")
print("           = 2(p×ŷ - ∑y_i)")
print()
print("  Second Derivative:")
print("  d²(SSE)/dŷ² = 2p > 0  (always POSITIVE for any p > 0)")
print()
print("  Properties:")
print("  ✓ The second derivative is a POSITIVE CONSTANT (2p)")
print("  ✓ This makes the SSE function CONVEX (concave upward)")
print("  ✓ The second derivative is MONOTONIC INCREASING (constant = 0-slope line)")
print("  ✓ SSE has a unique MINIMUM at ŷ = (∑y_i)/p = MEAN")
print()
print()

# ============= FINAL SUMMARY TABLE =============
print("=" * 100)
print("FINAL SUMMARY TABLE")
print("=" * 100)
print()
print(f"{'Question':<12} {'Topic':<35} {'Answer':<25} {'Value/Formula':<28}")
print("-" * 100)
print(f"{'Q1':<12} {'Initial Entropy H(S)':<35} {'0.9710':<25} {'Calculated':<28}")
print(f"{'Q2':<12} {'IG with A1':<35} {'0.1710':<25} {'Weighted entropy':<28}")
print(f"{'Q3':<12} {'IG with A2':<35} {'0.4200':<25} {'BEST SPLIT':<28}")
print(f"{'Q4':<12} {'IG with A3':<35} {'0.0200':<25} {'Lowest IG':<28}")
print(f"{'Q5':<12} {'First Split':<35} {'A2':<25} {'Highest IG':<28}")
print(f"{'Q6':<12} {'Second Split':<35} {'A1':<25} {'IG=0.9183':<28}")
print(f"{'Q7':<12} {'Decision Tree':<35} {'See diagram':<25} {'3-level tree':<28}")
print(f"{'Q8':<12} {'Mixed leaf prediction':<35} {'Majority class':<25} {'Minimizes error':<28}")
print(f"{'Q9':<12} {'Absolute Error':<35} {'min(p,n)':<25} {'Optimally classified':<28}")
print(f"{'Q10':<12} {'SSE Formula':<35} {'∑y²-2ŷ∑y+pŷ²':<25} {'Quadratic in ŷ':<28}")
print(f"{'Q11':<12} {'2nd Derivative':<35} {'2p (Positive)':<25} {'Monotonic increasing':<28}")
print()

print("=" * 100)
print("KEY INSIGHTS")
print("=" * 100)
print()
print("1. ENTROPY & INFORMATION GAIN:")
print("   - Entropy measures impurity (uncertainty) in a dataset")
print("   - Information Gain measures reduction in entropy from a split")
print("   - Select the attribute with MAXIMUM Information Gain")
print()
print("2. DECISION TREE CONSTRUCTION:")
print("   - Top-down, greedy approach using information gain")
print("   - First split: A2 (IG = 0.4200)")
print("   - Second split: A1 (IG = 0.9183 on A2=1 branch)")
print()
print("3. LEAF NODE PREDICTIONS:")
print("   - For classification: Use MAJORITY CLASS")
print("   - This minimizes absolute error")
print("   - Absolute Error = min(positive_count, negative_count)")
print()
print("4. REGRESSION TREES (SSE):")
print("   - Sum of Squared Errors: SSE = ∑(y_i - ŷ)²")
print("   - Optimal prediction: ŷ = MEAN of all values")
print("   - SSE is convex with unique minimum (d²SSE/dŷ² = 2p > 0)")
print()
print("=" * 100)
