import numpy as np

print("=" * 90)
print("QUESTIONS 8-11: DECISION TREE LEARNING CONCEPTS")
print("=" * 90)
print()

# ============= QUESTION 8 =============
print("=" * 90)
print("QUESTION 8: Mixed Examples in Leaf Nodes")
print("=" * 90)
print()

print("Context:")
print("--------")
print("In recursive construction of decision trees, sometimes a mixed set of positive")
print("and negative examples remains at a leaf node, even after all attributes have been used.")
print()
print("The decision tree LEARNING algorithm picks the MAJORITY class as the output.")
print("This is the classification that minimizes ABSOLUTE ERROR.")
print()
print("Majority classification = the label that appears most frequently in the leaf node")
print()

print("Analysis:")
print("---------")
print("For a mixed leaf node with k examples:")
print("  - If we predict Class 1: absolute error = number of Class 0 samples")
print("  - If we predict Class 0: absolute error = number of Class 1 samples")
print()
print("Majority classification minimizes the number of misclassified examples.")
print()

print("ANSWER TO QUESTION 8:")
print("The correct statement is:")
print("  ✓ 'Majority classification is the solution that minimizes absolute error.'")
print()

# ============= QUESTION 9 =============
print("=" * 90)
print("QUESTION 9: Absolute Error Calculation")
print("=" * 90)
print()

print("Context:")
print("--------")
print("For a leaf node where we have p positive examples and n negative examples.")
print("Suppose we predict the leaf node with value 1 (or 0).")
print()
print("Absolute Error calculation:")
print()

print("If prediction is 1 (positive):")
print("  - Correctly classify: p examples")
print("  - Misclassify: n examples")
print("  - Absolute Error = n (number of negative examples misclassified)")
print()

print("If prediction is 0 (negative):")
print("  - Correctly classify: n examples")
print("  - Misclassify: p examples")
print("  - Absolute Error = p (number of positive examples misclassified)")
print()

print("ANSWER TO QUESTION 9:")
print("The correct formulation is:")
print("  ✓ If prediction ∈ {1: then absolute error is p + 0 × n = p}")
print("  OR")
print("  ✓ If prediction ∈ {0: then absolute error is n + 0 × p = n}")
print()
print("More generally: Absolute Error = min(p, n)")
print()

# ============= QUESTION 10 =============
print("=" * 90)
print("QUESTION 10: Sum of Squared Errors (SSE)")
print("=" * 90)
print()

print("Context:")
print("--------")
print("For regression trees, we use Sum of Squared Errors (SSE) as the criterion.")
print()
print("Given p examples in a leaf node where:")
print("  - Actual value for example i: y_i")
print("  - Predicted value (class mean): ŷ")
print()

print("Formula for Sum of Squared Errors:")
print("---------------------------------")
print()
print("SSE = ∑(y_i - ŷ)²  for i = 1 to p")
print()
print("Expanded form:")
print("SSE = ∑y_i² - 2ŷ∑y_i + p×ŷ²")
print()

print("ANSWER TO QUESTION 10:")
print("The correct formula is:")
print("  ✓ SSE = ∑y_i² - 2ŷ∑y_i + p×ŷ²")
print()
print("This is the standard sum of squared residuals formula.")
print()

# ============= QUESTION 11 =============
print("=" * 90)
print("QUESTION 11: Derivative of SSE and Monotonic Properties")
print("=" * 90)
print()

print("Context:")
print("--------")
print("To minimize SSE, we take the derivative with respect to ŷ (predicted value).")
print()

print("Given: SSE = ∑y_i² - 2ŷ∑y_i + p×ŷ²")
print()
print("First Derivative:")
print("-----------------")
print("d(SSE)/dŷ = 0 - 2∑y_i + 2p×ŷ")
print("          = 2(p×ŷ - ∑y_i)")
print()

print("Second Derivative:")
print("------------------")
print("d²(SSE)/dŷ² = 2p > 0  (always positive)")
print()
print("Since the second derivative is positive, the function is:")
print("  ✓ CONVEX (concave upward)")
print("  ✓ Has a unique MINIMUM at the critical point")
print()

print("Critical Point (setting first derivative = 0):")
print("----------------------------------------------")
print("2(p×ŷ - ∑y_i) = 0")
print("p×ŷ = ∑y_i")
print("ŷ = ∑y_i / p = MEAN/AVERAGE")
print()

print("Analysis:")
print("---------")
print("The first derivative d(SSE)/dŷ = 2(p×ŷ - ∑y_i):")
print()
print("  - When ŷ < mean: d(SSE)/dŷ < 0 (decreasing, slope is negative)")
print("  - When ŷ = mean: d(SSE)/dŷ = 0 (minimum)")
print("  - When ŷ > mean: d(SSE)/dŷ > 0 (increasing, slope is positive)")
print()

print("ANSWER TO QUESTION 11:")
print("The correct statement is:")
print("  ✓ 'The second derivative of sum of square errors is monotonic increasing'")
print()
print("OR more precisely:")
print("  ✓ 'The SSE function is convex with a unique minimum at the average'")
print()

# ============= COMPREHENSIVE SUMMARY =============
print()
print("=" * 90)
print("COMPLETE ANSWERS SUMMARY")
print("=" * 90)
print()
print("Question 8:  Majority classification minimizes absolute error")
print("Question 9:  Absolute Error = min(p, n) where p=positive, n=negative examples")
print("Question 10: SSE = ∑y_i² - 2ŷ∑y_i + p×ŷ²")
print("Question 11: Second derivative is monotonic increasing (positive)")
print()
